// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Authentication.proto
// Protobuf C++ Version: 4.26.0-dev

#include "Authentication.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Authentication {

inline constexpr CreateAccountWebSuccess::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        requestid_{::int64_t{0}},
        userid_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR CreateAccountWebSuccess::CreateAccountWebSuccess(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CreateAccountWebSuccessDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateAccountWebSuccessDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateAccountWebSuccessDefaultTypeInternal() {}
  union {
    CreateAccountWebSuccess _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateAccountWebSuccessDefaultTypeInternal _CreateAccountWebSuccess_default_instance_;

inline constexpr CreateAccountWebFailure::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        requestid_{::int64_t{0}},
        reason_{static_cast< ::Authentication::CreateAccountWebFailure_Reason >(1)} {}

template <typename>
PROTOBUF_CONSTEXPR CreateAccountWebFailure::CreateAccountWebFailure(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CreateAccountWebFailureDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateAccountWebFailureDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateAccountWebFailureDefaultTypeInternal() {}
  union {
    CreateAccountWebFailure _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateAccountWebFailureDefaultTypeInternal _CreateAccountWebFailure_default_instance_;

inline constexpr CreateAccountWeb::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        email_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        plaintextpassword_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        requestid_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR CreateAccountWeb::CreateAccountWeb(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CreateAccountWebDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateAccountWebDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateAccountWebDefaultTypeInternal() {}
  union {
    CreateAccountWeb _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateAccountWebDefaultTypeInternal _CreateAccountWeb_default_instance_;

inline constexpr AuthenticateWebSuccess::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        creationdate_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        requestid_{::int64_t{0}},
        userid_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR AuthenticateWebSuccess::AuthenticateWebSuccess(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AuthenticateWebSuccessDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthenticateWebSuccessDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthenticateWebSuccessDefaultTypeInternal() {}
  union {
    AuthenticateWebSuccess _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthenticateWebSuccessDefaultTypeInternal _AuthenticateWebSuccess_default_instance_;

inline constexpr AuthenticateWebFailure::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        requestid_{::int64_t{0}},
        reason_{static_cast< ::Authentication::AuthenticateWebFailure_Reason >(1)} {}

template <typename>
PROTOBUF_CONSTEXPR AuthenticateWebFailure::AuthenticateWebFailure(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AuthenticateWebFailureDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthenticateWebFailureDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthenticateWebFailureDefaultTypeInternal() {}
  union {
    AuthenticateWebFailure _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthenticateWebFailureDefaultTypeInternal _AuthenticateWebFailure_default_instance_;

inline constexpr AuthenticateWeb::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        email_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        plaintextpassword_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        requestid_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR AuthenticateWeb::AuthenticateWeb(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AuthenticateWebDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthenticateWebDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthenticateWebDefaultTypeInternal() {}
  union {
    AuthenticateWeb _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthenticateWebDefaultTypeInternal _AuthenticateWeb_default_instance_;
}  // namespace Authentication
static ::_pb::Metadata file_level_metadata_Authentication_2eproto[6];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Authentication_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Authentication_2eproto = nullptr;
const ::uint32_t
    TableStruct_Authentication_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWeb, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWeb, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWeb, _impl_.requestid_),
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWeb, _impl_.email_),
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWeb, _impl_.plaintextpassword_),
        2,
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWebSuccess, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWebSuccess, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWebSuccess, _impl_.requestid_),
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWebSuccess, _impl_.userid_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWebFailure, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWebFailure, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWebFailure, _impl_.requestid_),
        PROTOBUF_FIELD_OFFSET(::Authentication::CreateAccountWebFailure, _impl_.reason_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWeb, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWeb, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWeb, _impl_.requestid_),
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWeb, _impl_.email_),
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWeb, _impl_.plaintextpassword_),
        2,
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWebSuccess, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWebSuccess, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWebSuccess, _impl_.requestid_),
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWebSuccess, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWebSuccess, _impl_.creationdate_),
        1,
        2,
        0,
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWebFailure, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWebFailure, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWebFailure, _impl_.requestid_),
        PROTOBUF_FIELD_OFFSET(::Authentication::AuthenticateWebFailure, _impl_.reason_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::Authentication::CreateAccountWeb)},
        {14, 24, -1, sizeof(::Authentication::CreateAccountWebSuccess)},
        {26, 36, -1, sizeof(::Authentication::CreateAccountWebFailure)},
        {38, 49, -1, sizeof(::Authentication::AuthenticateWeb)},
        {52, 63, -1, sizeof(::Authentication::AuthenticateWebSuccess)},
        {66, 76, -1, sizeof(::Authentication::AuthenticateWebFailure)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::Authentication::_CreateAccountWeb_default_instance_._instance,
    &::Authentication::_CreateAccountWebSuccess_default_instance_._instance,
    &::Authentication::_CreateAccountWebFailure_default_instance_._instance,
    &::Authentication::_AuthenticateWeb_default_instance_._instance,
    &::Authentication::_AuthenticateWebSuccess_default_instance_._instance,
    &::Authentication::_AuthenticateWebFailure_default_instance_._instance,
};
const char descriptor_table_protodef_Authentication_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024Authentication.proto\022\016Authentication\"O"
    "\n\020CreateAccountWeb\022\021\n\trequestId\030\001 \001(\003\022\r\n"
    "\005email\030\002 \001(\t\022\031\n\021plaintextPassword\030\003 \001(\t\""
    "<\n\027CreateAccountWebSuccess\022\021\n\trequestId\030"
    "\001 \001(\003\022\016\n\006userId\030\002 \001(\003\"\303\001\n\027CreateAccountW"
    "ebFailure\022\021\n\trequestId\030\001 \001(\003\022>\n\006reason\030\002"
    " \001(\0162..Authentication.CreateAccountWebFa"
    "ilure.Reason\"U\n\006Reason\022\032\n\026ACCOUNT_ALREAD"
    "Y_EXISTS\020\001\022\024\n\020INVALID_PASSWORD\020\002\022\031\n\025INTE"
    "RNAL_SERVER_ERROR\020\003\"N\n\017AuthenticateWeb\022\021"
    "\n\trequestId\030\001 \001(\003\022\r\n\005email\030\002 \001(\t\022\031\n\021plai"
    "ntextPassword\030\003 \001(\t\"Q\n\026AuthenticateWebSu"
    "ccess\022\021\n\trequestId\030\001 \001(\003\022\016\n\006userId\030\002 \001(\003"
    "\022\024\n\014creationDate\030\003 \001(\t\"\250\001\n\026AuthenticateW"
    "ebFailure\022\021\n\trequestId\030\001 \001(\003\022=\n\006reason\030\002"
    " \001(\0162-.Authentication.AuthenticateWebFai"
    "lure.Reason\"<\n\006Reason\022\027\n\023INVALID_CREDENT"
    "IALS\020\001\022\031\n\025INTERNAL_SERVER_ERROR\020\002"
};
static ::absl::once_flag descriptor_table_Authentication_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Authentication_2eproto = {
    false,
    false,
    713,
    descriptor_table_protodef_Authentication_2eproto,
    "Authentication.proto",
    &descriptor_table_Authentication_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_Authentication_2eproto::offsets,
    file_level_metadata_Authentication_2eproto,
    file_level_enum_descriptors_Authentication_2eproto,
    file_level_service_descriptors_Authentication_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Authentication_2eproto_getter() {
  return &descriptor_table_Authentication_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Authentication_2eproto(&descriptor_table_Authentication_2eproto);
namespace Authentication {
const ::google::protobuf::EnumDescriptor* CreateAccountWebFailure_Reason_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Authentication_2eproto);
  return file_level_enum_descriptors_Authentication_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CreateAccountWebFailure_Reason_internal_data_[] = {
    196609u, 0u, };
bool CreateAccountWebFailure_Reason_IsValid(int value) {
  return 1 <= value && value <= 3;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr CreateAccountWebFailure_Reason CreateAccountWebFailure::ACCOUNT_ALREADY_EXISTS;
constexpr CreateAccountWebFailure_Reason CreateAccountWebFailure::INVALID_PASSWORD;
constexpr CreateAccountWebFailure_Reason CreateAccountWebFailure::INTERNAL_SERVER_ERROR;
constexpr CreateAccountWebFailure_Reason CreateAccountWebFailure::Reason_MIN;
constexpr CreateAccountWebFailure_Reason CreateAccountWebFailure::Reason_MAX;
constexpr int CreateAccountWebFailure::Reason_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* AuthenticateWebFailure_Reason_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Authentication_2eproto);
  return file_level_enum_descriptors_Authentication_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t AuthenticateWebFailure_Reason_internal_data_[] = {
    131073u, 0u, };
bool AuthenticateWebFailure_Reason_IsValid(int value) {
  return 1 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr AuthenticateWebFailure_Reason AuthenticateWebFailure::INVALID_CREDENTIALS;
constexpr AuthenticateWebFailure_Reason AuthenticateWebFailure::INTERNAL_SERVER_ERROR;
constexpr AuthenticateWebFailure_Reason AuthenticateWebFailure::Reason_MIN;
constexpr AuthenticateWebFailure_Reason AuthenticateWebFailure::Reason_MAX;
constexpr int AuthenticateWebFailure::Reason_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class CreateAccountWeb::_Internal {
 public:
  using HasBits = decltype(std::declval<CreateAccountWeb>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CreateAccountWeb, _impl_._has_bits_);
};

CreateAccountWeb::CreateAccountWeb(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Authentication.CreateAccountWeb)
}
inline PROTOBUF_NDEBUG_INLINE CreateAccountWeb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        email_(arena, from.email_),
        plaintextpassword_(arena, from.plaintextpassword_) {}

CreateAccountWeb::CreateAccountWeb(
    ::google::protobuf::Arena* arena,
    const CreateAccountWeb& from)
    : ::google::protobuf::Message(arena) {
  CreateAccountWeb* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.requestid_ = from._impl_.requestid_;

  // @@protoc_insertion_point(copy_constructor:Authentication.CreateAccountWeb)
}
inline PROTOBUF_NDEBUG_INLINE CreateAccountWeb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        email_(arena),
        plaintextpassword_(arena) {}

inline void CreateAccountWeb::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.requestid_ = {};
}
CreateAccountWeb::~CreateAccountWeb() {
  // @@protoc_insertion_point(destructor:Authentication.CreateAccountWeb)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CreateAccountWeb::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.email_.Destroy();
  _impl_.plaintextpassword_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CreateAccountWeb::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      _data_ = {
          CreateAccountWeb::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
              PROTOBUF_FIELD_OFFSET(CreateAccountWeb, _impl_._cached_size_),
      };
  return &_data_;
}
PROTOBUF_NOINLINE void CreateAccountWeb::Clear() {
// @@protoc_insertion_point(message_clear_start:Authentication.CreateAccountWeb)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.email_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.plaintextpassword_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.requestid_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CreateAccountWeb::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 62, 2> CreateAccountWeb::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CreateAccountWeb, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CreateAccountWeb_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Authentication::CreateAccountWeb>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int64 requestId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CreateAccountWeb, _impl_.requestid_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(CreateAccountWeb, _impl_.requestid_)}},
    // optional string email = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(CreateAccountWeb, _impl_.email_)}},
    // optional string plaintextPassword = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(CreateAccountWeb, _impl_.plaintextpassword_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 requestId = 1;
    {PROTOBUF_FIELD_OFFSET(CreateAccountWeb, _impl_.requestid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional string email = 2;
    {PROTOBUF_FIELD_OFFSET(CreateAccountWeb, _impl_.email_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string plaintextPassword = 3;
    {PROTOBUF_FIELD_OFFSET(CreateAccountWeb, _impl_.plaintextpassword_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\37\0\5\21\0\0\0\0"
    "Authentication.CreateAccountWeb"
    "email"
    "plaintextPassword"
  }},
};

::uint8_t* CreateAccountWeb::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Authentication.CreateAccountWeb)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int64 requestId = 1;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_requestid(), target);
  }

  // optional string email = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_email();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "Authentication.CreateAccountWeb.email");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional string plaintextPassword = 3;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_plaintextpassword();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "Authentication.CreateAccountWeb.plaintextPassword");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Authentication.CreateAccountWeb)
  return target;
}

::size_t CreateAccountWeb::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Authentication.CreateAccountWeb)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional string email = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_email());
    }

    // optional string plaintextPassword = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_plaintextpassword());
    }

    // optional int64 requestId = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_requestid());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CreateAccountWeb::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CreateAccountWeb*>(&to_msg);
  auto& from = static_cast<const CreateAccountWeb&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Authentication.CreateAccountWeb)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_email(from._internal_email());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_plaintextpassword(from._internal_plaintextpassword());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.requestid_ = from._impl_.requestid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CreateAccountWeb::CopyFrom(const CreateAccountWeb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Authentication.CreateAccountWeb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CreateAccountWeb::IsInitialized() const {
  return true;
}

void CreateAccountWeb::InternalSwap(CreateAccountWeb* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.plaintextpassword_, &other->_impl_.plaintextpassword_, arena);
        swap(_impl_.requestid_, other->_impl_.requestid_);
}

::google::protobuf::Metadata CreateAccountWeb::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Authentication_2eproto_getter, &descriptor_table_Authentication_2eproto_once,
      file_level_metadata_Authentication_2eproto[0]);
}
// ===================================================================

class CreateAccountWebSuccess::_Internal {
 public:
  using HasBits = decltype(std::declval<CreateAccountWebSuccess>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CreateAccountWebSuccess, _impl_._has_bits_);
};

CreateAccountWebSuccess::CreateAccountWebSuccess(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Authentication.CreateAccountWebSuccess)
}
CreateAccountWebSuccess::CreateAccountWebSuccess(
    ::google::protobuf::Arena* arena, const CreateAccountWebSuccess& from)
    : CreateAccountWebSuccess(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CreateAccountWebSuccess::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CreateAccountWebSuccess::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, requestid_),
           0,
           offsetof(Impl_, userid_) -
               offsetof(Impl_, requestid_) +
               sizeof(Impl_::userid_));
}
CreateAccountWebSuccess::~CreateAccountWebSuccess() {
  // @@protoc_insertion_point(destructor:Authentication.CreateAccountWebSuccess)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CreateAccountWebSuccess::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CreateAccountWebSuccess::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      _data_ = {
          CreateAccountWebSuccess::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
              PROTOBUF_FIELD_OFFSET(CreateAccountWebSuccess, _impl_._cached_size_),
      };
  return &_data_;
}
PROTOBUF_NOINLINE void CreateAccountWebSuccess::Clear() {
// @@protoc_insertion_point(message_clear_start:Authentication.CreateAccountWebSuccess)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.requestid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.userid_) -
        reinterpret_cast<char*>(&_impl_.requestid_)) + sizeof(_impl_.userid_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CreateAccountWebSuccess::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> CreateAccountWebSuccess::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CreateAccountWebSuccess, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CreateAccountWebSuccess_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Authentication::CreateAccountWebSuccess>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int64 userId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CreateAccountWebSuccess, _impl_.userid_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(CreateAccountWebSuccess, _impl_.userid_)}},
    // optional int64 requestId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CreateAccountWebSuccess, _impl_.requestid_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(CreateAccountWebSuccess, _impl_.requestid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 requestId = 1;
    {PROTOBUF_FIELD_OFFSET(CreateAccountWebSuccess, _impl_.requestid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int64 userId = 2;
    {PROTOBUF_FIELD_OFFSET(CreateAccountWebSuccess, _impl_.userid_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CreateAccountWebSuccess::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Authentication.CreateAccountWebSuccess)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int64 requestId = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_requestid(), target);
  }

  // optional int64 userId = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_userid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Authentication.CreateAccountWebSuccess)
  return target;
}

::size_t CreateAccountWebSuccess::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Authentication.CreateAccountWebSuccess)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional int64 requestId = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_requestid());
    }

    // optional int64 userId = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_userid());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CreateAccountWebSuccess::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CreateAccountWebSuccess*>(&to_msg);
  auto& from = static_cast<const CreateAccountWebSuccess&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Authentication.CreateAccountWebSuccess)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.requestid_ = from._impl_.requestid_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.userid_ = from._impl_.userid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CreateAccountWebSuccess::CopyFrom(const CreateAccountWebSuccess& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Authentication.CreateAccountWebSuccess)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CreateAccountWebSuccess::IsInitialized() const {
  return true;
}

void CreateAccountWebSuccess::InternalSwap(CreateAccountWebSuccess* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CreateAccountWebSuccess, _impl_.userid_)
      + sizeof(CreateAccountWebSuccess::_impl_.userid_)
      - PROTOBUF_FIELD_OFFSET(CreateAccountWebSuccess, _impl_.requestid_)>(
          reinterpret_cast<char*>(&_impl_.requestid_),
          reinterpret_cast<char*>(&other->_impl_.requestid_));
}

::google::protobuf::Metadata CreateAccountWebSuccess::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Authentication_2eproto_getter, &descriptor_table_Authentication_2eproto_once,
      file_level_metadata_Authentication_2eproto[1]);
}
// ===================================================================

class CreateAccountWebFailure::_Internal {
 public:
  using HasBits = decltype(std::declval<CreateAccountWebFailure>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CreateAccountWebFailure, _impl_._has_bits_);
};

CreateAccountWebFailure::CreateAccountWebFailure(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Authentication.CreateAccountWebFailure)
}
CreateAccountWebFailure::CreateAccountWebFailure(
    ::google::protobuf::Arena* arena, const CreateAccountWebFailure& from)
    : CreateAccountWebFailure(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CreateAccountWebFailure::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        reason_{static_cast< ::Authentication::CreateAccountWebFailure_Reason >(1)} {}

inline void CreateAccountWebFailure::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.requestid_ = {};
}
CreateAccountWebFailure::~CreateAccountWebFailure() {
  // @@protoc_insertion_point(destructor:Authentication.CreateAccountWebFailure)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CreateAccountWebFailure::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CreateAccountWebFailure::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      _data_ = {
          CreateAccountWebFailure::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
              PROTOBUF_FIELD_OFFSET(CreateAccountWebFailure, _impl_._cached_size_),
      };
  return &_data_;
}
PROTOBUF_NOINLINE void CreateAccountWebFailure::Clear() {
// @@protoc_insertion_point(message_clear_start:Authentication.CreateAccountWebFailure)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    _impl_.requestid_ = ::int64_t{0};
    _impl_.reason_ = 1;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CreateAccountWebFailure::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> CreateAccountWebFailure::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CreateAccountWebFailure, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CreateAccountWebFailure_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Authentication::CreateAccountWebFailure>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .Authentication.CreateAccountWebFailure.Reason reason = 2;
    {::_pbi::TcParser::FastEr1S1,
     {16, 1, 3, PROTOBUF_FIELD_OFFSET(CreateAccountWebFailure, _impl_.reason_)}},
    // optional int64 requestId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CreateAccountWebFailure, _impl_.requestid_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(CreateAccountWebFailure, _impl_.requestid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 requestId = 1;
    {PROTOBUF_FIELD_OFFSET(CreateAccountWebFailure, _impl_.requestid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional .Authentication.CreateAccountWebFailure.Reason reason = 2;
    {PROTOBUF_FIELD_OFFSET(CreateAccountWebFailure, _impl_.reason_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
  }}, {{
    {1, 3},
  }}, {{
  }},
};

::uint8_t* CreateAccountWebFailure::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Authentication.CreateAccountWebFailure)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int64 requestId = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_requestid(), target);
  }

  // optional .Authentication.CreateAccountWebFailure.Reason reason = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_reason(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Authentication.CreateAccountWebFailure)
  return target;
}

::size_t CreateAccountWebFailure::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Authentication.CreateAccountWebFailure)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional int64 requestId = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_requestid());
    }

    // optional .Authentication.CreateAccountWebFailure.Reason reason = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_reason());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CreateAccountWebFailure::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CreateAccountWebFailure*>(&to_msg);
  auto& from = static_cast<const CreateAccountWebFailure&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Authentication.CreateAccountWebFailure)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.requestid_ = from._impl_.requestid_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.reason_ = from._impl_.reason_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CreateAccountWebFailure::CopyFrom(const CreateAccountWebFailure& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Authentication.CreateAccountWebFailure)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CreateAccountWebFailure::IsInitialized() const {
  return true;
}

void CreateAccountWebFailure::InternalSwap(CreateAccountWebFailure* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CreateAccountWebFailure, _impl_.reason_)
      + sizeof(CreateAccountWebFailure::_impl_.reason_)
      - PROTOBUF_FIELD_OFFSET(CreateAccountWebFailure, _impl_.requestid_)>(
          reinterpret_cast<char*>(&_impl_.requestid_),
          reinterpret_cast<char*>(&other->_impl_.requestid_));
}

::google::protobuf::Metadata CreateAccountWebFailure::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Authentication_2eproto_getter, &descriptor_table_Authentication_2eproto_once,
      file_level_metadata_Authentication_2eproto[2]);
}
// ===================================================================

class AuthenticateWeb::_Internal {
 public:
  using HasBits = decltype(std::declval<AuthenticateWeb>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AuthenticateWeb, _impl_._has_bits_);
};

AuthenticateWeb::AuthenticateWeb(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Authentication.AuthenticateWeb)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateWeb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        email_(arena, from.email_),
        plaintextpassword_(arena, from.plaintextpassword_) {}

AuthenticateWeb::AuthenticateWeb(
    ::google::protobuf::Arena* arena,
    const AuthenticateWeb& from)
    : ::google::protobuf::Message(arena) {
  AuthenticateWeb* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.requestid_ = from._impl_.requestid_;

  // @@protoc_insertion_point(copy_constructor:Authentication.AuthenticateWeb)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateWeb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        email_(arena),
        plaintextpassword_(arena) {}

inline void AuthenticateWeb::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.requestid_ = {};
}
AuthenticateWeb::~AuthenticateWeb() {
  // @@protoc_insertion_point(destructor:Authentication.AuthenticateWeb)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthenticateWeb::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.email_.Destroy();
  _impl_.plaintextpassword_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AuthenticateWeb::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      _data_ = {
          AuthenticateWeb::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
              PROTOBUF_FIELD_OFFSET(AuthenticateWeb, _impl_._cached_size_),
      };
  return &_data_;
}
PROTOBUF_NOINLINE void AuthenticateWeb::Clear() {
// @@protoc_insertion_point(message_clear_start:Authentication.AuthenticateWeb)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.email_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.plaintextpassword_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.requestid_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AuthenticateWeb::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 61, 2> AuthenticateWeb::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AuthenticateWeb, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AuthenticateWeb_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Authentication::AuthenticateWeb>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int64 requestId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AuthenticateWeb, _impl_.requestid_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(AuthenticateWeb, _impl_.requestid_)}},
    // optional string email = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(AuthenticateWeb, _impl_.email_)}},
    // optional string plaintextPassword = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(AuthenticateWeb, _impl_.plaintextpassword_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 requestId = 1;
    {PROTOBUF_FIELD_OFFSET(AuthenticateWeb, _impl_.requestid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional string email = 2;
    {PROTOBUF_FIELD_OFFSET(AuthenticateWeb, _impl_.email_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string plaintextPassword = 3;
    {PROTOBUF_FIELD_OFFSET(AuthenticateWeb, _impl_.plaintextpassword_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\0\5\21\0\0\0\0"
    "Authentication.AuthenticateWeb"
    "email"
    "plaintextPassword"
  }},
};

::uint8_t* AuthenticateWeb::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Authentication.AuthenticateWeb)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int64 requestId = 1;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_requestid(), target);
  }

  // optional string email = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_email();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "Authentication.AuthenticateWeb.email");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional string plaintextPassword = 3;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_plaintextpassword();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "Authentication.AuthenticateWeb.plaintextPassword");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Authentication.AuthenticateWeb)
  return target;
}

::size_t AuthenticateWeb::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Authentication.AuthenticateWeb)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional string email = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_email());
    }

    // optional string plaintextPassword = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_plaintextpassword());
    }

    // optional int64 requestId = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_requestid());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AuthenticateWeb::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AuthenticateWeb*>(&to_msg);
  auto& from = static_cast<const AuthenticateWeb&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Authentication.AuthenticateWeb)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_email(from._internal_email());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_plaintextpassword(from._internal_plaintextpassword());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.requestid_ = from._impl_.requestid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthenticateWeb::CopyFrom(const AuthenticateWeb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Authentication.AuthenticateWeb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AuthenticateWeb::IsInitialized() const {
  return true;
}

void AuthenticateWeb::InternalSwap(AuthenticateWeb* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.plaintextpassword_, &other->_impl_.plaintextpassword_, arena);
        swap(_impl_.requestid_, other->_impl_.requestid_);
}

::google::protobuf::Metadata AuthenticateWeb::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Authentication_2eproto_getter, &descriptor_table_Authentication_2eproto_once,
      file_level_metadata_Authentication_2eproto[3]);
}
// ===================================================================

class AuthenticateWebSuccess::_Internal {
 public:
  using HasBits = decltype(std::declval<AuthenticateWebSuccess>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AuthenticateWebSuccess, _impl_._has_bits_);
};

AuthenticateWebSuccess::AuthenticateWebSuccess(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Authentication.AuthenticateWebSuccess)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateWebSuccess::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        creationdate_(arena, from.creationdate_) {}

AuthenticateWebSuccess::AuthenticateWebSuccess(
    ::google::protobuf::Arena* arena,
    const AuthenticateWebSuccess& from)
    : ::google::protobuf::Message(arena) {
  AuthenticateWebSuccess* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, requestid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, requestid_),
           offsetof(Impl_, userid_) -
               offsetof(Impl_, requestid_) +
               sizeof(Impl_::userid_));

  // @@protoc_insertion_point(copy_constructor:Authentication.AuthenticateWebSuccess)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateWebSuccess::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        creationdate_(arena) {}

inline void AuthenticateWebSuccess::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, requestid_),
           0,
           offsetof(Impl_, userid_) -
               offsetof(Impl_, requestid_) +
               sizeof(Impl_::userid_));
}
AuthenticateWebSuccess::~AuthenticateWebSuccess() {
  // @@protoc_insertion_point(destructor:Authentication.AuthenticateWebSuccess)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthenticateWebSuccess::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.creationdate_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AuthenticateWebSuccess::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      _data_ = {
          AuthenticateWebSuccess::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
              PROTOBUF_FIELD_OFFSET(AuthenticateWebSuccess, _impl_._cached_size_),
      };
  return &_data_;
}
PROTOBUF_NOINLINE void AuthenticateWebSuccess::Clear() {
// @@protoc_insertion_point(message_clear_start:Authentication.AuthenticateWebSuccess)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.creationdate_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.requestid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.userid_) -
        reinterpret_cast<char*>(&_impl_.requestid_)) + sizeof(_impl_.userid_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AuthenticateWebSuccess::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 58, 2> AuthenticateWebSuccess::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AuthenticateWebSuccess, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AuthenticateWebSuccess_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Authentication::AuthenticateWebSuccess>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int64 requestId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AuthenticateWebSuccess, _impl_.requestid_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(AuthenticateWebSuccess, _impl_.requestid_)}},
    // optional int64 userId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AuthenticateWebSuccess, _impl_.userid_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(AuthenticateWebSuccess, _impl_.userid_)}},
    // optional string creationDate = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(AuthenticateWebSuccess, _impl_.creationdate_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 requestId = 1;
    {PROTOBUF_FIELD_OFFSET(AuthenticateWebSuccess, _impl_.requestid_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int64 userId = 2;
    {PROTOBUF_FIELD_OFFSET(AuthenticateWebSuccess, _impl_.userid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional string creationDate = 3;
    {PROTOBUF_FIELD_OFFSET(AuthenticateWebSuccess, _impl_.creationdate_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\45\0\0\14\0\0\0\0"
    "Authentication.AuthenticateWebSuccess"
    "creationDate"
  }},
};

::uint8_t* AuthenticateWebSuccess::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Authentication.AuthenticateWebSuccess)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int64 requestId = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_requestid(), target);
  }

  // optional int64 userId = 2;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_userid(), target);
  }

  // optional string creationDate = 3;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_creationdate();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "Authentication.AuthenticateWebSuccess.creationDate");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Authentication.AuthenticateWebSuccess)
  return target;
}

::size_t AuthenticateWebSuccess::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Authentication.AuthenticateWebSuccess)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional string creationDate = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_creationdate());
    }

    // optional int64 requestId = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_requestid());
    }

    // optional int64 userId = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_userid());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AuthenticateWebSuccess::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AuthenticateWebSuccess*>(&to_msg);
  auto& from = static_cast<const AuthenticateWebSuccess&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Authentication.AuthenticateWebSuccess)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_creationdate(from._internal_creationdate());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.requestid_ = from._impl_.requestid_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.userid_ = from._impl_.userid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthenticateWebSuccess::CopyFrom(const AuthenticateWebSuccess& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Authentication.AuthenticateWebSuccess)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AuthenticateWebSuccess::IsInitialized() const {
  return true;
}

void AuthenticateWebSuccess::InternalSwap(AuthenticateWebSuccess* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.creationdate_, &other->_impl_.creationdate_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AuthenticateWebSuccess, _impl_.userid_)
      + sizeof(AuthenticateWebSuccess::_impl_.userid_)
      - PROTOBUF_FIELD_OFFSET(AuthenticateWebSuccess, _impl_.requestid_)>(
          reinterpret_cast<char*>(&_impl_.requestid_),
          reinterpret_cast<char*>(&other->_impl_.requestid_));
}

::google::protobuf::Metadata AuthenticateWebSuccess::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Authentication_2eproto_getter, &descriptor_table_Authentication_2eproto_once,
      file_level_metadata_Authentication_2eproto[4]);
}
// ===================================================================

class AuthenticateWebFailure::_Internal {
 public:
  using HasBits = decltype(std::declval<AuthenticateWebFailure>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AuthenticateWebFailure, _impl_._has_bits_);
};

AuthenticateWebFailure::AuthenticateWebFailure(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Authentication.AuthenticateWebFailure)
}
AuthenticateWebFailure::AuthenticateWebFailure(
    ::google::protobuf::Arena* arena, const AuthenticateWebFailure& from)
    : AuthenticateWebFailure(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateWebFailure::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        reason_{static_cast< ::Authentication::AuthenticateWebFailure_Reason >(1)} {}

inline void AuthenticateWebFailure::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.requestid_ = {};
}
AuthenticateWebFailure::~AuthenticateWebFailure() {
  // @@protoc_insertion_point(destructor:Authentication.AuthenticateWebFailure)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthenticateWebFailure::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AuthenticateWebFailure::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      _data_ = {
          AuthenticateWebFailure::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
              PROTOBUF_FIELD_OFFSET(AuthenticateWebFailure, _impl_._cached_size_),
      };
  return &_data_;
}
PROTOBUF_NOINLINE void AuthenticateWebFailure::Clear() {
// @@protoc_insertion_point(message_clear_start:Authentication.AuthenticateWebFailure)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    _impl_.requestid_ = ::int64_t{0};
    _impl_.reason_ = 1;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AuthenticateWebFailure::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> AuthenticateWebFailure::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AuthenticateWebFailure, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AuthenticateWebFailure_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Authentication::AuthenticateWebFailure>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .Authentication.AuthenticateWebFailure.Reason reason = 2;
    {::_pbi::TcParser::FastEr1S1,
     {16, 1, 2, PROTOBUF_FIELD_OFFSET(AuthenticateWebFailure, _impl_.reason_)}},
    // optional int64 requestId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AuthenticateWebFailure, _impl_.requestid_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(AuthenticateWebFailure, _impl_.requestid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 requestId = 1;
    {PROTOBUF_FIELD_OFFSET(AuthenticateWebFailure, _impl_.requestid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional .Authentication.AuthenticateWebFailure.Reason reason = 2;
    {PROTOBUF_FIELD_OFFSET(AuthenticateWebFailure, _impl_.reason_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
  }}, {{
    {1, 2},
  }}, {{
  }},
};

::uint8_t* AuthenticateWebFailure::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Authentication.AuthenticateWebFailure)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int64 requestId = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_requestid(), target);
  }

  // optional .Authentication.AuthenticateWebFailure.Reason reason = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_reason(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Authentication.AuthenticateWebFailure)
  return target;
}

::size_t AuthenticateWebFailure::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Authentication.AuthenticateWebFailure)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional int64 requestId = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_requestid());
    }

    // optional .Authentication.AuthenticateWebFailure.Reason reason = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_reason());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AuthenticateWebFailure::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AuthenticateWebFailure*>(&to_msg);
  auto& from = static_cast<const AuthenticateWebFailure&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Authentication.AuthenticateWebFailure)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.requestid_ = from._impl_.requestid_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.reason_ = from._impl_.reason_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthenticateWebFailure::CopyFrom(const AuthenticateWebFailure& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Authentication.AuthenticateWebFailure)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AuthenticateWebFailure::IsInitialized() const {
  return true;
}

void AuthenticateWebFailure::InternalSwap(AuthenticateWebFailure* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AuthenticateWebFailure, _impl_.reason_)
      + sizeof(AuthenticateWebFailure::_impl_.reason_)
      - PROTOBUF_FIELD_OFFSET(AuthenticateWebFailure, _impl_.requestid_)>(
          reinterpret_cast<char*>(&_impl_.requestid_),
          reinterpret_cast<char*>(&other->_impl_.requestid_));
}

::google::protobuf::Metadata AuthenticateWebFailure::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Authentication_2eproto_getter, &descriptor_table_Authentication_2eproto_once,
      file_level_metadata_Authentication_2eproto[5]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Authentication
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
